# Generated by Django 2.2.3 on 2019-07-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prcie',
            new_name='price',
        ),
    ]
